create table employess_detail(
emp_id int primary key ,
name varchar not null,
age int default 0,
department varchar not null,
salary int default 0,
city varchar not null
)
copy employess_detail from 'D:\Data Analyst\sql\table250\employees_250_rows.csv'Delimiter ','csv header;
select * from employess_detail
SELECT * FROM employess_detail WHERE emp_id = 10;
SELECT * FROM employess_detail WHERE emp_id > 100;
SELECT * FROM employess_detail WHERE emp_id < 50;
SELECT * FROM employess_detail WHERE age = 25;
SELECT * FROM employess_detail WHERE age > 30;
SELECT * FROM employess_detail WHERE age < 22;
SELECT * FROM employess_detail WHERE salary = 50000;
SELECT * FROM employess_detail WHERE salary > 100000;
SELECT * FROM employess_detail WHERE salary < 40000;
SELECT * FROM employess_detail WHERE department = 'IT';
SELECT * FROM employess_detail WHERE department = 'HR';
SELECT * FROM employess_detail WHERE city = 'Mumbai';
SELECT * FROM employess_detail WHERE city = 'Delhi';
SELECT * FROM employess_detail WHERE city = 'Pune';
SELECT * FROM employess_detail WHERE name = 'Emp_50';
SELECT * FROM employess_detail WHERE name = 'Emp_100';
SELECT * FROM employess_detail WHERE emp_id >= 200;
SELECT * FROM employess_detail WHERE emp_id <= 20;
SELECT * FROM employess_detail WHERE salary >= 75000;
SELECT * FROM employess_detail WHERE salary <= 35000;
SELECT * FROM employess_detail WHERE age > 25 AND salary > 60000;
SELECT * FROM employess_detail WHERE age < 30 AND salary < 50000;
SELECT * FROM employess_detail WHERE department='IT' AND city='Pune';
SELECT * FROM employess_detail WHERE department='HR' AND city='Mumbai';
SELECT * FROM employess_detail WHERE department='Finance' AND city='Delhi';
SELECT * FROM employess_detail WHERE age=25 AND department='IT';
SELECT * FROM employess_detail WHERE age=30 AND salary=50000;
SELECT * FROM employess_detail WHERE age>28 AND city='Bangalore';
SELECT * FROM employess_detail WHERE salary>80000 AND city='Delhi';
SELECT * FROM employess_detail WHERE salary<40000 AND city='Chennai';
SELECT * FROM employess_detail WHERE age BETWEEN 25 AND 30 AND city='Pune';
SELECT * FROM employess_detail WHERE age BETWEEN 20 AND 25 AND department='HR';
SELECT * FROM employess_detail WHERE salary BETWEEN 50000 AND 80000 AND department='IT';
SELECT * FROM employess_detail WHERE emp_id>100 AND city='Mumbai';
SELECT * FROM employess_detail WHERE emp_id<50 AND department='Sales';
SELECT * FROM employess_detail WHERE emp_id BETWEEN 10 AND 20 AND city='Delhi';
SELECT * FROM employess_detail WHERE emp_id BETWEEN 200 AND 220 AND department='IT';
SELECT * FROM employess_detail WHERE age>25 AND department='Marketing';
SELECT * FROM employess_detail WHERE age<30 AND department='Finance';
SELECT * FROM employess_detail WHERE salary>100000 AND department='HR';
SELECT * FROM employess_detail WHERE city='Mumbai' OR city='Delhi';
SELECT * FROM employess_detail WHERE department='IT' OR department='HR';
SELECT * FROM employess_detail WHERE age=25 OR age=30;
SELECT * FROM employess_detail WHERE salary>100000 OR salary<40000;
SELECT * FROM employess_detail WHERE emp_id=1 OR emp_id=250;
SELECT * FROM employess_detail WHERE city='Chennai' OR city='Pune';
SELECT * FROM employess_detail WHERE department='Finance' OR department='Sales';
SELECT * FROM employess_detail WHERE age<22 OR age>32;
SELECT * FROM employess_detail WHERE salary BETWEEN 40000 AND 60000 OR city='Mumbai';
SELECT * FROM employess_detail WHERE emp_id BETWEEN 50 AND 100 OR department='IT';
SELECT * FROM employess_detail WHERE emp_id<20 OR city='Delhi';
SELECT * FROM employess_detail WHERE emp_id>200 OR city='Bangalore';
SELECT * FROM employess_detail WHERE salary>120000 OR age<25;
SELECT * FROM employess_detail WHERE age>30 OR department='HR';
SELECT * FROM employess_detail WHERE department='Marketing' OR salary<35000;
SELECT * FROM employess_detail WHERE emp_id=5 OR emp_id=10 OR emp_id=15;
SELECT * FROM employess_detail WHERE city='Mumbai' OR city='Pune' OR city='Delhi';
SELECT * FROM employess_detail WHERE age IN (21,22,23) OR department='IT';
SELECT * FROM employess_detail WHERE salary IN (50000,60000) OR city='Chennai';
SELECT * FROM employess_detail WHERE department='Sales' OR emp_id BETWEEN 1 AND 10;
SELECT * FROM employess_detail WHERE city IN ('Mumbai','Delhi');
SELECT * FROM employess_detail WHERE city NOT IN ('Mumbai','Delhi');
SELECT * FROM employess_detail WHERE department IN ('IT','HR');
SELECT * FROM employess_detail WHERE department NOT IN ('Finance','Sales');
SELECT * FROM employess_detail WHERE age IN (21,25,30);
SELECT * FROM employess_detail WHERE age NOT IN (20,22);
SELECT * FROM employess_detail WHERE emp_id IN (1,50,100,150,200);
SELECT * FROM employess_detail WHERE emp_id NOT IN (10,20,30);
SELECT * FROM employess_detail WHERE salary IN (50000,75000,100000);
SELECT * FROM employess_detail WHERE salary NOT IN (30000,35000);
SELECT * FROM employess_detail WHERE city IN ('Pune','Chennai') AND department='IT';
SELECT * FROM employess_detail WHERE city NOT IN ('Bangalore') AND salary>50000;
SELECT * FROM employess_detail WHERE department IN ('HR','Finance') AND age>25;
SELECT * FROM employess_detail WHERE department NOT IN ('IT') AND age<30;
SELECT * FROM employess_detail WHERE emp_id IN (5,10,15,20);
SELECT * FROM employess_detail WHERE emp_id NOT IN (100,200);
SELECT * FROM employess_detail WHERE salary IN (40000,45000,50000);
SELECT * FROM employess_detail WHERE salary NOT IN (60000,70000);
SELECT * FROM employess_detail WHERE age IN (20,21,22);
SELECT * FROM employess_detail WHERE age NOT IN (30,31,32);

UPDATE employess_detail SET salary = salary + 5000 WHERE department='IT';
UPDATE employess_detail SET salary = salary + 3000 WHERE department='HR';
UPDATE employess_detail SET salary = salary + 2000 WHERE department='Finance';
UPDATE employess_detail SET city='Mumbai' WHERE city='Pune';
UPDATE employess_detail SET city='Delhi' WHERE city='Chennai';
UPDATE employess_detail SET age = age + 1 WHERE emp_id <= 50;
UPDATE employess_detail SET age = age - 1 WHERE emp_id > 200;
UPDATE employess_detail SET department='Admin' WHERE department='HR';
UPDATE employess_detail SET salary=60000 WHERE emp_id=10;
UPDATE employess_detail SET salary=70000 WHERE emp_id=20;
UPDATE employess_detail SET salary=80000 WHERE emp_id=30;
UPDATE employess_detail SET salary=90000 WHERE emp_id=40;
UPDATE employess_detail SET salary=100000 WHERE emp_id=50;
UPDATE employess_detail SET salary=salary*1.1 WHERE salary < 50000;
UPDATE employess_detail SET salary=salary*1.2 WHERE salary > 100000;
UPDATE employess_detail SET city='Bangalore' WHERE emp_id BETWEEN 10 AND 20;
UPDATE employess_detail SET department='IT' WHERE emp_id BETWEEN 30 AND 40;
UPDATE employess_detail SET salary=75000 WHERE age BETWEEN 25 AND 30;
UPDATE employess_detail SET salary=85000 WHERE age BETWEEN 30 AND 35;
UPDATE employess_detail SET city='Hyderabad' WHERE city IN ('Mumbai','Delhi');
UPDATE employess_detail SET department='Support' WHERE department IN ('Sales','Marketing');
UPDATE employess_detail SET salary=salary+1000 WHERE emp_id IN (1,2,3,4,5);
UPDATE employess_detail SET age=28 WHERE emp_id IN (10,20,30);
UPDATE employess_detail SET salary=65000 WHERE emp_id IN (100,150,200);
UPDATE employess_detail SET city='Chennai' WHERE emp_id IN (25,50,75);
UPDATE employess_detail SET salary=salary-2000 WHERE department='Finance';
UPDATE employess_detail SET salary=salary+500 WHERE department='Sales';
UPDATE employess_detail SET department='HR' WHERE name LIKE 'Emp_1%';
UPDATE employess_detail SET city='Delhi' WHERE name LIKE '%0';
UPDATE employess_detail SET salary=50000 WHERE name LIKE '%50%';
UPDATE employess_detail SET salary=salary+2000 WHERE age>30;
UPDATE employess_detail SET salary=salary-1000 WHERE age<25;
UPDATE employess_detail SET department='IT' WHERE salary>100000;
UPDATE employess_detail SET department='Junior' WHERE salary<40000;
UPDATE employess_detail SET city='Remote' WHERE salary>120000;
UPDATE employess_detail SET city='Office' WHERE salary<50000;
UPDATE employess_detail SET salary=salary+3000 WHERE city='Mumbai';
UPDATE employess_detail SET salary=salary+2000 WHERE city='Delhi';
UPDATE employess_detail SET salary=salary+1000 WHERE city='Pune';
UPDATE employess_detail SET salary=salary+1500 WHERE city='Chennai';
UPDATE employess_detail SET salary=salary+1800 WHERE city='Bangalore';
UPDATE employess_detail SET age=age+2 WHERE department='IT';
UPDATE employess_detail SET age=age+1 WHERE department='HR';
UPDATE employess_detail SET age=age+3 WHERE department='Finance';
UPDATE employess_detail SET age=age+2 WHERE department='Sales';
UPDATE employess_detail SET age=age+1 WHERE department='Marketing';
UPDATE employess_detail SET salary=salary+5000 WHERE emp_id%2=0;
UPDATE employess_detail SET salary=salary+2500 WHERE emp_id%2!=0;
UPDATE employess_detail SET department='Senior' WHERE age>30;
UPDATE employess_detail SET department='Junior' WHERE age<=25;


